# .travis.yml
sudo: false
language: cpp
before_install:
  - sudo apt update
  - sudo apt-key adv --keyserver keyserver.ubuntu.com --recv-keys 6B05F25D762E3157
  - sudo apt install -y doxygen qt5-default libvtk7-qt-dev
# Build your code
script:
- mkdir build
- doxygen Doxyfile
- cd build
- cmake ..
- make
- make test
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: build/html
  github_token: $GH_REPO_TOKEN
  on:
    branch: master